site_name: 开源之道 - The Open Source Way Guidebook
docs_dir: 'docs'
repo_url: https://github.com/OpenCubikFoundation/theopensourceway-guidebook-zh
repo_name: OpenCubikFoundation/theopensourceway-guidebook-zh
edit_uri: edit/main/docs/

site_author: OpenCubikFoundation & 所有贡献者
copyright: Licensed under Creative Commons Attribution 4.0 International License.

theme:
  name: material
  language: zh
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables

nav:
  - 欢迎使用 MkDocs: index.md
  - 参与贡献:
    - 格式手册: contribution/format-guide.md

plugins:
  - search
  - with-pdf:
      #author: Contributors
      #copyright: Licensed under Creative Commons Attribution-NonCommercial 4.0 International License.
      
      cover: true
      back_cover: true
      cover_title: 开源之道
      cover_subtitle: The Open Source Way Guidebook
      #custom_template_path: TEMPLATES PATH
        
      toc_title: 目录
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #   - 'release-notes/:upgrading'
      #   - 'release-notes/:changelog'

      #exclude_pages:
      #   - 'bugs/'
      #   - 'appendix/contribute/'
      #convert_iframe:
      #   - src: IFRAME SRC
      #     img: POSTER IMAGE URL
      #     text: ALTERNATE TEXT
      #   - src: ...
      #two_columns_level: 3
        
      #render_js: true
      #headless_chrome_path: headless-chromium
      
      #enabled_if_env: ENABLE_PDF_EXPORT
        
      #debug_html: true
      #show_anchors: true
      #verbose: true
